### ISSUE TITLE
🐛 Program Dashboard - Molecular data isn't coming through and chart/table aren't reflecting same data

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/roadmap#857]
## Describe the bug
In QA: There are some discrepancies for the molecular data on the program dashboard between the table and the molecular data summary chart

## Noticed Cases

- [ ] **PACA-CA** - there are 2 donors with open VF but it's not reflected on the chart
![image](https://user-images.githubusercontent.com/18424138/146249104-04a89964-0450-4b6d-9207-c7eab9132604.png)

- [ ] **RDPCDEV-CA** - same as above, one donor has Open VF but it's not reflected on chart
- [ ] ROSI-RU - there's a lot of molecular data in the table, but the chart is still at zero. Is that because the donors are invalid because of a clinical data issue? 
![image](https://user-images.githubusercontent.com/18424138/146249414-e7cbffe5-a27b-4468-8cd0-af018621a37f.png)

- [ ] **TCRB-CA** - the open VF table data isn't reflected in the chart. Also, @lindaxiang has reported there should be 4 alignments, 2 Sanger VC and 2 mutect2 reported here too
![image](https://user-images.githubusercontent.com/18424138/146249709-bf5e1442-b79c-4114-a11f-42e1177b92b8.png)

- [ ] **TEST-PR** - table and chart don't seem to be reflecting the same data either
![image](https://user-images.githubusercontent.com/18424138/146249888-a6a16b8d-ffa7-4737-9754-f767d403c25e.png)

- [ ] **TEST-QA** - table and chart aren't reflecting the same data. Also this is a case where the donors have partially released files
![image](https://user-images.githubusercontent.com/18424138/146250071-52e5c8f8-0805-47de-8efa-e10dd9781df4.png)

**Comment by Buwujiu** [comment]
There are two problems that caused the issues on donor dashboard: 
1. for all programs that are missing data in the `Molecular Summary Data` chart, the root cause is that `first_published_at` ES field is `null` in analysis centric indices. The fix for this is this pr: https://github.com/overture-stack/maestro/issues/222. 
2. program `TCRB-CA` workflow data doesn't match the actual runs is caused by missing data in rdpc api due to an ES fuzzy search issue, which is fixed under this ticket: https://github.com/icgc-argo/workflow-roadmap/issues/211.

**Comment by akachru-github** [comment]
- Fixed Maestro and Workflow Relay are both deployed to QA. This is testable in QA. 
- Investigate finding missing alignment for TCRB-CA

**Comment by kcullion** [comment]
@Buwujiu @lindaxiang there aren't many dashboards to test the molecular data on in QA. Perhaps you can help test by doing a brand new submission (maybe a bulk set), and run it through all the workflows to test the table and chart?

@Buwujiu I did notice one strange thing on PACA-CA - I see there are two donors with Open Access VF - but they don't have any tumour/normal submitted (or any other data for the other workflows). So they shouldn't be showing up on the chart, also the chart is saying there's a lot more donors for Open access vf. 

![image](https://user-images.githubusercontent.com/18424138/151865260-5579596f-08a7-4f3e-ada7-6d352ad316b0.png)

Something seems off with TEST-PR too:
![image](https://user-images.githubusercontent.com/18424138/151866665-f2cd0c14-0819-42b0-97b0-001b7ec16c29.png)

In TEST-QA:
![image](https://user-images.githubusercontent.com/18424138/151867242-429623b1-daeb-49e2-9618-80ccba485e06.png)

**Comment by Buwujiu** [comment]
@kcullion TEST-PR and PACA-CA are not ready for test yet, because of song performance issue, we need to update maestro to use new song endpoint to be able to index TEST-PR and PACA-CA. Right now they are still showing old data. TCRB-CA needs investigation too, I will talk with Linda tomorrow.

**Comment by kcullion** [comment]
thanks @Buwujiu ... I moved this ticket back to "in progress" then, since it's not quite ready to test.

**Comment by Buwujiu** [comment]
@akachru-github @kcullion I made two tickets for tracking remaining issues listed in this ticket: 
https://github.com/icgc-argo/roadmap/issues/874
https://github.com/icgc-argo/roadmap/issues/873

**Comment by kcullion** [comment]
thanks @Buwujiu ...as discussed on slack, we'll leave this ticket open for re-testing the bugs found before

**Comment by kcullion** [comment]
discussed on slack...
```
TEST-PR is missing data in rdpc, we don’t really need to worry too much about it
same with PACA-CA
```
Made this bug ticket for TEST-QA inconsistency https://github.com/icgc-argo/roadmap/issues/875

**Comment by akachru-github** [comment]
@kcullion , can this be closed given the Huntress and the Eiger release is now in production?

**Comment by kcullion** [comment]
@akachru-github yes I think we can close this!
